# Generated by Django 2.2.5 on 2019-12-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletcomment',
            old_name='bulletItem',
            new_name='bullet_item',
        ),
        migrations.RenameField(
            model_name='bulletitem',
            old_name='bookTitle',
            new_name='book_title',
        ),
        migrations.AlterField(
            model_name='bulletcomment',
            name='content',
            field=models.CharField(help_text='Post a comment on the share', max_length=1000),
        ),
    ]
