# Generated by Django 2.2.5 on 2019-12-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191202_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcollections',
            name='book_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bookcollections',
            name='isbn',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookcollections',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
